### ISSUE TITLE
New deploy to pub.dartlang.org ?

### ISSUE THREAD

**Issue by tomaszkubacki** [DirectMyFile/console.dart#14]
I see that there are changes in repo but not published to pub.dartlang.org (pub version is >1yr old) - Examples in repo are out of sync with that what is in repo.
Can new version be published to pub ?

https://pub.dartlang.org/packages/console

**Comment by kaendfinger** [comment]
Sure

**Comment by tomaszkubacki** [comment]
awesome - thanks!
