### ISSUE TITLE
Color.bright is for nothing

### ISSUE THREAD

**Issue by Rodsevich** [DirectMyFile/console.dart#18]
https://github.com/DirectMyFile/console.dart/blob/9123cabe97b43e89defd6d31d7dfdaa21c169610/lib/src/color.dart#L60-L64

It's the same code

**Comment by jeremymeadows** [comment]
I just submitted a pull request that changes that :)
![colors dart](https://user-images.githubusercontent.com/37280013/79677780-f5b9a400-81b1-11ea-8fb8-df43347c1827.png)

**Comment by Rodsevich** [comment]
Hope they accept it, I think this is dead sadly

**Comment by lgorence** [comment]
Fixed via #24. Thank you @jeremymeadows :smiley:
